apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-logging
  namespace: kube-system
  labels:
    app: fluentd-logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/*.log
      pos_file /var/log/fluentd/tmp/access.log.pos
      tag foo.*
      <parse>
        @type json
      </parse>
    </source>
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
    <match fluentd.**>
      @type null
    </match>
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>
    <filter kubernetes.var.log.containers.**>
      @type record_transformer
      enable_ruby
      remove_keys kubernetes, docker
      <record>
        k8s_service ${ record.dig("kubernetes", "labels", "app") }
        service k8s_${ record.dig("kubernetes", "labels", "app") }
        k8s_namespace ${ record.dig("kubernetes", "namespace_name") }
        k8s_instance ${ record.dig("kubernetes", "pod_name") }
        instance k8s_${ record.dig("kubernetes", "pod_name") }
        cluster_name hai-hn
      </record>
    </filter>

    <match kubernetes.var.log.containers.**hai-hn-namespace**.**>
      @type copy
      <store>
        @type loki
        url "localhost:9012"
        username loki
        password loki
        # extra_labels {"env":"dev"}
        label_keys "service, k8s_instance, cluster_name, k8s_service, k8s_namespace, instance"
        flush_interval 10s
        flush_at_shutdown true
        buffer_chunk_limit 1m
      </store>
      <store>
        @type stdout
      </store>
    </match>