{
 "title": "k8s node",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Host:",
    "query": "label_values(node_uname_info{}, nodename)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "cpu busy",
   "type": "graph",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\"}) by (cpu))",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "ram used",
   "type": "graph",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:$port\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:$port\"})",
     "legendFormat": "ram"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "graph",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\"}",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\"} - node_boot_time_seconds{instance=~\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\"} - (node_memory_Cached_bytes{instance=~\"$node:$port\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$node:$port\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}