{
 "title": "k8s service",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(container_memory_usage_bytes{container_name!=\"POD\"},namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"},created_by_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container_name!=\"POD\",pod=~\"$pod.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "mem used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod=~\"$pod.*\",pod_template_hash=\"\", namespace=\"$namespace\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "net io",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"^$pod.*\"}[1m]))",
     "legendFormat": "recv"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod=~\"^$pod.*\"}[1m]))",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}